#!/bin/sh

usage () {
    cat <<EOF
Usage: ${0##*/} [-h|--help] [DIR]

    -h, --help:  Show this help.
    DIR:         Directory containing the slides.
EOF
}

quit () {
    trap - EXIT

    # Clear the screen.
    printf '\e[2J'

    cursor_goto "$LINES" 0

    # Show the cursor.
    printf '\e[?25h'
    printf '\r'

    [ "$old_tty_cfg" ] && stty "$old_tty_cfg"
    exit 0
}

cursor_goto () {
    printf '\e[%sH' "${1};${2}"
}

show_current_slide () {
    current_slide=$(printf '%s\n' "$SLIDES" | sed -n $((I + 1))p )

    # Clear the screen in place.
    cursor_goto 0 0
    x=$LINES
    while [ "$x" -gt 0 ]
    do
        # Clear the current line.
        printf '\e[2K'
        # Move the cursor down one line.
        printf '\e[1B'
        x=$((x - 1))
    done
    cursor_goto 0 0

    if [ "$I" -eq "$TOTAL" ]; then
        cursor_goto $((LINES / 2 - 1)) $((COLUMNS / 2 - 2))
        printf END.
        return
    else
        cut -c-"$COLUMNS" "$current_slide" | head -$((LINES - 2))
    fi

    # Write slide number at bottom left.
    cursor_goto "$LINES" 0
    printf %d/%d $((I+1)) "$TOTAL"
}

trap quit INT QUIT TERM EXIT

for arg do
    case $arg in
        --help|-h) usage; exit 0 ;;
    esac
done

WORK_DIR=${1:-.}
SLIDES=$(printf '%s\n' "$WORK_DIR"/* | LANG=C sort)
TOTAL=$(printf '%s\n' "$WORK_DIR"/* | wc -l)
I=0

# Save terminal options to be restored on exit.
old_tty_cfg=$(stty -g)
stty -icanon

# Get screen geometry.
LINES=$(tput lines)
COLUMNS=$(tput cols)

# Hide the cursor.
printf '\e[?25l'

while true; do
    # clamp I
    [ "$I" -lt 0 ] && I=0
    [ "$I" -gt "$TOTAL" ] && I=$TOTAL

    show_current_slide

    # Navigation
    case $(dd ibs=1 count=1 2>/dev/null) in
        [jn])   [ "$I" -eq "$TOTAL" ] && quit; I=$((I + 1)) ;;
        [kpN])  I=$((I - 1)) ;;
        [g0])   I=0 ;;
        G)      I=$((TOTAL - 1)) ;;
        q)      quit ;;
        *)
    esac
done
